### ISSUE TITLE
[BUG] Version 112 freezes when opening a new page

### ISSUE THREAD

**Issue by aleehedl** [Sparticuz/chromium#80]
## Environment
* `chromium` Version: 112
* `puppeteer` / `puppeteer-core` Version: 19.8.0
* Node.js Version: 18.15.0
* Lambda / GCF Runtime: x86_64 Image

## Expected Behavior
Launching the browser should work

## Current Behavior
Browser silently hangs without any errors

## Steps to Reproduce
I use this code in AWS Lambda Docker image. Chromium is built into the image to `/opt/chr/chromium`. All the uncompressed files files from `require('@sparticus/chromium').executablePath()` are moved to `/opt/chr` and `LD_LIBRARY_PATH` is adjusted accordingly.

```js
  ...
  const executablePath = process.env.AWS_EXECUTION_ENV
    ? path.join('/opt', 'chr', 'chromium')
    : puppeteer.executablePath();

  const browser = await puppeteer.launch({
    args: chromium.args,
    defaultViewport: chromium.defaultViewport,
    executablePath,
    headless: chromium.headless,
    ignoreHTTPSErrors: true,
  });
  const page = await browser.newPage();    // <--- This is where it hangs
  await page.setContent(html);
  ...
```

## Possible Solution

Downgrading this library to version 111 fixes the issue. I'm looking for a more future-proof solution :-)

**Comment by pjg** [comment]
Not sure if related, but version 112 hangs for me while being executed in a Docker image based AWS Lambda context. The error I'm seeing is this:

```
prctl(PR_SET_NO_NEW_PRIVS) failed
```

**Comment by Sparticuz** [comment]
The two things i would try,

1) set `chromium.setHeadlessMode = true`. This will set the headless mode for 112 back to legacy. This should be done before launching chromium.

2) investigate the new args and see if one of the new ones is causing problems. I basically copied all of puppeteers default args, which we were missing some, so maybe one of them is the problem.

**Comment by Sparticuz** [comment]
Also try `args: [...chromium.args, "--single-process"]`

**Comment by pjg** [comment]
I can confirm that using version `112.0.0` works.

**Comment by pjg** [comment]
Adding `--single-process` arg to `112.0.1` also makes it work.

**Comment by Sparticuz** [comment]
Fixed in 112.0.2

**Comment by yspreen** [comment]
@Sparticuz I don't think it's fixed I'm still seeing this behaviour
