### ISSUE TITLE
Running puppeteer gatsby netlify function

### ISSUE THREAD

**Issue by kdichev** [Sparticuz/chromium#96]
Hi I am trying to use gatsby netlify function with puppeteer but I am running in quite a few issues when my app is deployed to netlify. I’ve found a few topics with the issue but haven’t found the solution for this yet. Hence I am creating this issue.

when I try to trigger the puppeteer function I get this error:
`Error when executing function “create-pdf.ts”: “Could not find Chrome (ver. 112.0.5615.121). This can occur if either 1. you did not perform an installation before running the script (e.g. npm install) or 2. your cache path is incorrectly configured (which is: /home/sbx_user1051/.cache/puppeteer). For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.”`

I’ve added [@sparticuz](https://answers.netlify.com/u/sparticuz)/chromium and suggested fixes from this repo but then I get this erorr:

`Error when executing function “create-pdf.ts”: “The input directory “/var/task/.cache/bin” does not exist.”`

I've made a simple reproduction repo: https://github.com/kdichev/gatsby-netlify-puppeteer-function/pull/1/files

But I've still haven't managed to make it work. I've also made a netlify support thread with all my findings
https://answers.netlify.com/t/running-puppeteer-gatsby-netlify-function/91453/1

I know that this could not be issue with sparticuz/chromium but I want to get more feedback if possible. If you feel that this is not for here feel free to close. Thanks a lot!

**Comment by kdichev** [comment]
> That error means that your bin folder, with the chromium.br file, is somewhere else. I've not used netlify,

This is also my findings as I've done some debugging and the default paths used are not there at all so the bin folder is somewhere else indeed. I've found some "fixes" in this repo for netlify that ensures that the external package is kept but seems like it's not working anymore or I've got some issue with my implementation.

https://github.com/Sparticuz/chromium/issues/24#issuecomment-1414107620

I will continue the research and will probably make a doc page here when I find the solution , hopefully with the help of netlify support.

**Comment by kdichev** [comment]
ok so I probably managed to find the place for chromium.br file is by checking netlify docs for external node modules, i had to update `netlify.toml` like so:

```
[[plugins]]
    package = "@netlify/plugin-gatsby"
[functions]
    node_bundler = "esbuild"
    external_node_modules = ["@sparticuz/chromium"]
```

had to add `node_bundler` to `esbuild` as stated by netlify docs in order to use `external_node_modules `
then needed to update the code with the proper path to the file 

```
  const browser = await puppeteer.launch({
    args: chromium.args,
    defaultViewport: chromium.defaultViewport,
    executablePath: await chromium.executablePath(
      "/var/task/node_modules/@sparticuz/chromium/bin"
    ),
    headless: chromium.headless,
  });
 ```
 correct path is `/var/task/node_modules/@sparticuz/chromium/bin`
 
 although this beringed me closer to the solution I still got an error:
 ```
 Error when executing function "create-pdf.ts": "Failed to launch the browser process!
/tmp/chromium: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
```

which is the same as using `@sparticuz/chromium-min` with the url `https://github.com/Sparticuz/chromium/releases/download/v113.0.0/chromium-v113.0.0-pack.tar`

so I guess this is working but still have issue with the libnss3.so

wondering now what's the next step heh

**Comment by Sparticuz** [comment]
> I tried with `@sparticuz/chromium-min` and I am getting a different error:
> 
> > Error: Failed to launch the browser process!
> > /tmp/chromium: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory

That means that the AWS package isn't being extracted. Can you get me the output of the `AWS_EXECUTION_ENV` environment variable?

**Comment by Sparticuz** [comment]
I published 113.0.1 that will look for that env var and extract the aws pack as well.

**Comment by kdichev** [comment]
@Sparticuz I've tested both of my branches `@sparticuz/chromium` and `@sparticuz/chromium-min` with the latest version but I still get the same error

**Comment by Sparticuz** [comment]
It checks that the `AWS_LAMBDA_JS_RUNTIME` env var starts with `nodejs` https://github.com/Sparticuz/chromium/pull/98/files#diff-0f2cb7ff7dfccabe7dbdb4b008cdfad1ab1a9003144226d414e5e817715dbacb. A look at process.env would help.

**Comment by kdichev** [comment]
unfortunately is still failing with the same error:
https://deploy-preview-1--gatsby-netlify-puppeteer-function.netlify.app/ chromium
https://deploy-preview-3--gatsby-netlify-puppeteer-function.netlify.app/ chromium-min

logging this is truly: 

```js
console.log(
    process.env["AWS_LAMBDA_JS_RUNTIME"] &&
      /^nodejs/.test(process.env["AWS_LAMBDA_JS_RUNTIME"]) === true
 );
 ```

**Comment by kdichev** [comment]
@Sparticuz you have an idea what else could be wrong?

**Comment by Astevens521** [comment]
Hi kdichev, I struggled with the same situation and was successful simple action, hope this can help you.
\* still failing page and browser close, I want to close this page and open a new page.

```
    "@netlify/functions": "^1.4.0",
    "puppeteer-core": "^20.1.1",
    "@sparticuz/chromium-min": "^113.0.1",
```

learned from kdichev
_netlify.toml_
```
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@sparticuz/chromium-min"]
```

_.../netlify/functions/chromium_test.ts_
```
import { Handler } from "@netlify/functions";
import puppeteer from "puppeteer-core";
import chromium from "@sparticuz/chromium-min";

const handler: Handler = async () => {
  const browser = await puppeteer.launch({
    args: chromium.args,
    defaultViewport: chromium.defaultViewport,
    executablePath: await chromium.executablePath("https://github.com/Sparticuz/chromium/releases/download/v113.0.1/chromium-v113.0.1-pack.tar"),
    headless: chromium.headless,
  });

  try {
    const page = await browser.newPage();
    await page.goto("https://example.com");
    const pageTitle = await page.title();
    console.log("page title: ", pageTitle);
  } catch (err) {
    console.error("error", err.message);
  } finally {
    // some reason: dont return "await Page.close" & "await Browser.close" only Production
    browser.close();
  }

  return { statusCode: 200, body: "" };
};

export { handler };
```

**Comment by samlogan** [comment]
Hey, @nikme, how did you resolve the following error?

```
/tmp/chromium: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
```

I am stuck here with the Gatsby Netlify function I am working on.

**Comment by nikme** [comment]
> Hey, @nikme, how did you resolve the following error?
> 
> ```
> /tmp/chromium: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
> ```
> 
> I am stuck here with the Gatsby Netlify function I am working on.

@samlogan I didn't get this error =(

**Comment by ayushrana182** [comment]
@samlogan were you able to get past that issue? I'm stuck there too! please share what worked for you if you did, much appreciated!
